<?php

namespace Biopen\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends DocumentRepository
{
}
