<?php

namespace Biopen\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

use Biopen\CoreBundle\Document\NewsletterFrequencyOptions;
/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
	public function findNeedsToReceiveNewsletter()
	{
      $qb = $this->createQueryBuilder('BiopenGeoDirectoryBundle:User');
      return $qb->field('newsletterFrequency')->gt(NewsletterFrequencyOptions::Never)               
                ->field('nextNewsletterDate')->lte(new \DateTime())
                ->getQuery()->execute();
	}


}
