<?php

namespace Biopen\CoreBundle\Repository;

/**
 * WrapperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WrapperRepository extends \Doctrine\ORM\EntityRepository
{
}
