<?php

namespace Biopen\FournisseurBundle\Repository;

/**
 * ClassesHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassesHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
