<?php

namespace Biopen\FournisseurBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends EntityRepository
{
	public function myfindAll()
	{

	 $qb = $this->createQueryBuilder('fournisseur');

    // On fait une jointure avec l'entité Advert avec pour alias « adv »
    $qb
      ->join('fournisseur.produits', 'fourisseurProduit')
      ->addSelect('fourisseurProduit')
      ->join('fourisseurProduit.produit', 'produit')
      ->addSelect('produit');
    ;

    // Puis on ne retourne que $limit résultats
    //$qb->setMaxResults(10);

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
      ;
  	}
}
