<?php

namespace Biopen\FournisseurBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
