<?php

/**
 * This file is part of the MonVoisinFaitDuBio project.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @copyright Copyright (c) 2016 Sebastian Castro - 90scastro@gmail.com
 * @license    MIT License
 * @Last Modified time: 2016-09-01
 */
 

namespace Biopen\FournisseurBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{
	public function findFromPoint($distance, $point, $maxResult = 0)
	{	 
   $qb = $this->createQueryBuilder('provider');

    $qb = $this->_em->createQueryBuilder()
      ->select('provider as Provider, DISTANCE(provider.latlng, POINT_STR(:point))*100 AS distance')
      ->setParameter('point',$point)
      ->from($this->_entityName, 'provider')
      ->where('provider.valide = 0')
      ->andwhere('DISTANCE(provider.latlng, POINT_STR(:point))*100 < :distance')
      ->setParameter('distance', $distance)
      ->orderBy('distance')  
      ->leftjoin('provider.products', 'providerProduct')
      ->addSelect('providerProduct')
      ->leftjoin('providerProduct.product', 'product')
      ->addSelect('product');
    ;

    // Puis on ne retourne que $limit résultats
    if ($maxResult != 0) $qb->setMaxResults(intval($maxResult));

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
      ;
  	}

  public function findAllProviders()
  {  
   $qb = $this->createQueryBuilder('provider');

    $qb = $this->_em->createQueryBuilder()
      ->select('provider as Provider')
      ->from($this->_entityName, 'provider')
      ->where('provider.valide = 0')
      ->leftjoin('provider.products', 'providerProduct')
      ->addSelect('providerProduct')
      ->leftjoin('providerProduct.product', 'product')
      ->addSelect('product');
    ;

    // Puis on ne retourne que $limit résultats
    //$qb->setMaxResults(10);

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
      ;
    }
}
