<?php

namespace Biopen\GeoDirectoryBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository
{  
   public function findRootCategories()
   {
      $qb = $this->createQueryBuilder('BiopenGeoDirectoryBundle:Category');
      $qb->field('isRootCategory')->equals(true);
      return $qb->getQuery()->execute();
   }
}
