<?php

namespace Biopen\GeoDirectoryBundle\Repository;

/**
 * CategoryOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
