<?php

namespace Biopen\GeoDirectoryBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * OptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionRepository extends DocumentRepository
{
   public function findOptionsIdsWithText($text) 
   {
      $qbOption = $this->createQueryBuilder('BiopenGeoDirectoryBundle:Option');
      $expr = $qbOption->expr()->operator('$text', array('$search' => (string) $text));
      $qbOption  //->limit(50)
        ->equals($expr->getQuery())
        ->select('id');

      return $qbOption->hydrate(false)->getQuery()->execute()->toArray();   
   }
}
