<?php

namespace Biopen\GeoDirectoryBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionValueRepository extends DocumentRepository
{
}
