<?php

namespace Biopen\GeoDirectoryBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * OptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionRepository extends DocumentRepository
{
}
